In [1]:
#random module
import random
x=random.randint(0,9)
print(x)
y=random.random()
print(y)

5
0.42982550248845675


In [3]:
#numpy package
import numpy as np
a=np.array([35,1,34,36,27,48,49])
print(type(a))
b=np.zeros(3)
c=np.ones(4)
print(b)
print(c)
d=np.sort(a)
print(d)

<class 'numpy.ndarray'>
[0. 0. 0.]
[1. 1. 1. 1.]
[ 1 27 34 35 36 48 49]
